In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from pycaret.time_series import *
from sktime.forecasting.model_selection import SlidingWindowSplitter
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
warnings.filterwarnings('ignore')

In [2]:
%pip install 'pycaret[full]'

  Using cached shap-0.44.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached interpret-0.5.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached umap-learn-0.5.5.tar.gz (90 kB)
  Preparing metadata (setup.py) ... done
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /opt/homebrew/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/l

In [7]:
%pip install 'packaging==21.3'

  Using cached packaging-21.3-py3-none-any.whl.metadata (15 kB)
Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Attempting uninstall: packaging
    Found existing installation: packaging 23.2
    Uninstalling packaging-23.2:
      Successfully uninstalled packaging-23.2
Note: you may need to restart the kernel to use updated packages.


In [9]:
%pip install --upgrade 'packaging'
%pip install --upgrade 'pycaret'

  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
df = pd.read_csv("train.csv")

df = df[['DATETIMEDATA','PM25']]
df = df.set_index('DATETIMEDATA')
df

PM25
DATETIMEDATA             
2024-01-01 00:00:00  16.5
2024-01-01 01:00:00  33.6
2024-01-01 02:00:00  34.2
2024-01-01 03:00:00  20.1
2024-01-01 04:00:00  16.5
...                   ...
2024-02-28 19:00:00  23.6
2024-02-28 20:00:00  25.2
2024-02-28 21:00:00  23.2
2024-02-28 22:00:00  24.7
2024-02-28 23:00:00  19.8

[1416 rows x 1 columns]

In [3]:
from sktime.forecasting.model_selection import SlidingWindowSplitter

In [4]:
import numpy as np
from sktime.forecasting.model_selection import SlidingWindowSplitter
ts = np.arange(10)
splitter = SlidingWindowSplitter(fh=np.arange(1,3), window_length=3, step_length=1)
list(splitter.split(ts))

[(array([0, 1, 2]), array([3, 4])),
 (array([1, 2, 3]), array([4, 5])),
 (array([2, 3, 4]), array([5, 6])),
 (array([3, 4, 5]), array([6, 7])),
 (array([4, 5, 6]), array([7, 8])),
 (array([5, 6, 7]), array([8, 9]))]

In [5]:
df.size

1416

In [12]:
from sklearn.model_selection import TimeSeriesSplit
from pycaret.time_series import TSForecastingExperiment
from sktime.forecasting.model_selection import SlidingWindowSplitter
exp = TSForecastingExperiment()
exp.setup(data = df, target='PM25' ,coverage=0.90, fold_strategy=SlidingWindowSplitter(fh=np.arange(1,23), window_length=130, step_length=130)) # using the past 6 months data to make prediction for the next month and moving half a year forward. 

In [13]:
exp.plot_model(plot='train_test_split')


In [14]:
exp.compare_models(sort='rmse')


ThetaForecaster(sp=24)

In [15]:
ets = exp.create_model('ets')


In [16]:
tuned_ets = exp.tune_model(ets)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    3.8s finished


In [18]:
holdout_pred = exp.predict_model(tuned_ets)


In [19]:
holdout_pred

y_pred
2024-02-28 02:00  16.3722
2024-02-28 03:00  15.2906
2024-02-28 04:00  15.9119
2024-02-28 05:00  17.6367
2024-02-28 06:00  18.7088
2024-02-28 07:00  19.7007
2024-02-28 08:00  20.7016
2024-02-28 09:00  18.1012
2024-02-28 10:00  16.3520
2024-02-28 11:00  16.1068
2024-02-28 12:00  15.2807
2024-02-28 13:00  14.5832
2024-02-28 14:00  14.2197
2024-02-28 15:00  14.9879
2024-02-28 16:00  14.6287
2024-02-28 17:00  15.6036
2024-02-28 18:00  15.8284
2024-02-28 19:00  17.3697
2024-02-28 20:00  17.5841
2024-02-28 21:00  17.3881
2024-02-28 22:00  17.5351
2024-02-28 23:00  15.7574

In [20]:
final_model = exp.finalize_model(tuned_ets)


In [21]:
exp.plot_model(final_model, plot='forecast', data_kwargs={'fh':24})


In [22]:
unseen_predictions = exp.predict_model(final_model, fh=168)
unseen_predictions

y_pred
2024-02-29 00:00  21.1983
2024-02-29 01:00  20.9325
2024-02-29 02:00  21.3039
2024-02-29 03:00  19.9072
2024-02-29 04:00  20.8009
2024-02-29 05:00  23.0352
2024-02-29 06:00  24.4347
2024-02-29 07:00  25.7298
2024-02-29 08:00  27.0068
2024-02-29 09:00  23.6565