In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from pycaret.time_series import *
from sktime.forecasting.model_selection import SlidingWindowSplitter
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
warnings.filterwarnings('ignore')

In [2]:
%pip install 'pycaret[full]'

  Using cached shap-0.44.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached interpret-0.5.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached umap-learn-0.5.5.tar.gz (90 kB)
  Preparing metadata (setup.py) ... done
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /opt/homebrew/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/l

In [7]:
%pip install 'packaging==21.3'

  Using cached packaging-21.3-py3-none-any.whl.metadata (15 kB)
Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Attempting uninstall: packaging
    Found existing installation: packaging 23.2
    Uninstalling packaging-23.2:
      Successfully uninstalled packaging-23.2
Note: you may need to restart the kernel to use updated packages.


In [9]:
%pip install --upgrade 'packaging'
%pip install --upgrade 'pycaret'

  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [299]:
df = pd.read_csv("train.csv")
df = df.set_index('DATETIMEDATA')
df

PM25         O3  WS  TEMP    RH     WD
DATETIMEDATA                                               
2024-01-01 00:00:00  16.5  16.000000   1  27.0  79.0  115.0
2024-01-01 01:00:00  33.6  11.326513   1  27.0  82.0   97.0
2024-01-01 02:00:00  34.2  11.326513   1  26.0  84.0   96.0
2024-01-01 03:00:00  20.1  11.326513   1  26.0  82.0  108.0
2024-01-01 04:00:00  16.5   1.000000   1  27.0  79.0  106.0
...                   ...        ...  ..   ...   ...    ...
2024-02-28 19:00:00  23.6  11.326513   1  29.0  64.0  184.0
2024-02-28 20:00:00  25.2  11.326513   1  29.0  64.0  183.0
2024-02-28 21:00:00  23.2   1.000000   1  29.0  64.0  159.0
2024-02-28 22:00:00  24.7   3.000000   1  28.0  65.0  134.0
2024-02-28 23:00:00  19.8   6.000000   1  28.0  65.0   94.0

[1416 rows x 6 columns]

In [300]:
import numpy as np
from sktime.forecasting.model_selection import SlidingWindowSplitter
ts = np.arange(10)
splitter = SlidingWindowSplitter(fh=np.arange(1,3), window_length=3, step_length=1)
list(splitter.split(ts))

[(array([0, 1, 2]), array([3, 4])),
 (array([1, 2, 3]), array([4, 5])),
 (array([2, 3, 4]), array([5, 6])),
 (array([3, 4, 5]), array([6, 7])),
 (array([4, 5, 6]), array([7, 8])),
 (array([5, 6, 7]), array([8, 9]))]

In [301]:
df.size

8496

In [305]:
from sklearn.model_selection import TimeSeriesSplit
from pycaret.time_series import TSForecastingExperiment
from sktime.forecasting.model_selection import SlidingWindowSplitter
exp = TSForecastingExperiment()

exp.setup(data = df, target='PM25' ,coverage=0.90, fold_strategy=SlidingWindowSplitter(fh=np.arange(1,23), window_length=130, step_length=130)) # using the past 6 months data to make prediction for the next month and moving half a year forward. 

In [259]:
exp.plot_model(plot='train_test_split')


In [260]:
exp.compare_models(sort='rmse')


BaseCdsDtForecaster(fe_target_rr=[WindowSummarizer(lag_feature={'lag': [24, 23,
                                                                        22, 21,
                                                                        20, 19,
                                                                        18, 17,
                                                                        16, 15,
                                                                        14, 13,
                                                                        12, 11,
                                                                        10, 9,
                                                                        8, 7, 6,
                                                                        5, 4, 3,
                                                                        2, 1]},
                                                   n_jobs=1)],
                    regressor=HuberRegressor(), sp=24, window_length=24)

In [324]:
ets = exp.create_model('huber_cds_dt')


In [262]:
tuned_ets = exp.tune_model(ets)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    9.9s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   26.5s finished


In [331]:
holdout_pred = exp.predict_model(tuned_ets, verbose=True)

In [332]:
#predicting the future values 7 days
holdout_pred

y_pred
2024-02-28 02:00  13.9641
2024-02-28 03:00  12.9636
2024-02-28 04:00  15.0006
2024-02-28 05:00  17.2675
2024-02-28 06:00  17.8028
2024-02-28 07:00  19.4853
2024-02-28 08:00  19.7591
2024-02-28 09:00  17.9006
2024-02-28 10:00  17.3357
2024-02-28 11:00  16.7169
2024-02-28 12:00  15.2215
2024-02-28 13:00  14.1673
2024-02-28 14:00  14.2155
2024-02-28 15:00  14.7606
2024-02-28 16:00  14.5875
2024-02-28 17:00  15.5920
2024-02-28 18:00  16.4289
2024-02-28 19:00  17.6914
2024-02-28 20:00  18.2261
2024-02-28 21:00  18.4712
2024-02-28 22:00  18.7200
2024-02-28 23:00  16.6563

In [334]:
final_model = exp.finalize_model(tuned_ets)


In [368]:
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Assuming your data is stored in a DataFrame called df_train
endog = df['PM25']  # Endogenous variable (target variable)
exog = df[['O3', 'WS', 'TEMP', 'RH', 'WD']]  # Exogenous variables

# Define and train the SARIMAX model
model = SARIMAX(endog, exog=exog, order=(1, 0, 1), seasonal_order=(1, 1, 1, 24))
result = model.fit()

# Forecasting
forecast_horizon = 24  # Forecast horizon of 24 hours
forecast = result.forecast(steps=forecast_horizon, exog=exog.iloc[-forecast_horizon:])

# Extract the last datetime value from the train.csv DataFrame
last_datetime = df.index[-1]

# Create a new datetime index for the forecast DataFrame
forecast_index = pd.date_range(start=last_datetime, periods=forecast_horizon + 1, freq='H')[1:]

# Create a DataFrame with forecasted values and the new datetime index
forecast_df = pd.DataFrame({'DATETIMEDATA': forecast_index, 'PM25': forecast})

forecast_df

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           10     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.71728D+00    |proj g|=  1.61845D-01


 This problem is unconstrained.



At iterate    5    f=  2.69496D+00    |proj g|=  2.33319D-01

At iterate   10    f=  2.63236D+00    |proj g|=  2.78912D-02

At iterate   15    f=  2.62549D+00    |proj g|=  6.10178D-02

At iterate   20    f=  2.61930D+00    |proj g|=  1.76111D-02

At iterate   25    f=  2.61897D+00    |proj g|=  1.33228D-02

At iterate   30    f=  2.61842D+00    |proj g|=  5.24540D-02

At iterate   35    f=  2.61819D+00    |proj g|=  1.82471D-03

At iterate   40    f=  2.61814D+00    |proj g|=  1.34068D-02

At iterate   45    f=  2.61810D+00    |proj g|=  8.03296D-03

At iterate   50    f=  2.61808D+00    |proj g|=  1.69998D-03

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tn

DATETIMEDATA       PM25
1416 1970-01-01 01:00:00.000001415  19.955712
1417 1970-01-01 02:00:00.000001415  18.270442
1418 1970-01-01 03:00:00.000001415  17.604323
1419 1970-01-01 04:00:00.000001415  16.057907
1420 1970-01-01 05:00:00.000001415  18.010508
1421 1970-01-01 06:00:00.000001415  19.302733
1422 1970-01-01 07:00:00.000001415  20.544571
1423 1970-01-01 08:00:00.000001415  21.374697
1424 1970-01-01 09:00:00.000001415  21.700418
1425 1970-01-01 10:00:00.000001415  19.214231
1426 1970-01-01 11:00:00.000001415  18.036235
1427 1970-01-01 12:00:00.000001415  17.164243
1428 1970-01-01 13:00:00.000001415  15.614950
1429 1970-01-01 14:00:00.000001415  15.351543
1430 1970-01-01 15:00:00.000001415  14.989754
1431 1970-01-01 16:00:00.000001415  15.736224
1432 1970-01-01 17:00:00.000001415  15.799762
1433 1970-01-01 18:00:00.000001415  18.021360
1434 1970-01-01 19:00:00.000001415  19.693496
1435 1970-01-01 20:00:00.000001415  19.808021
1436 1970-01-01 21:00:00.000001415  20.233833
1437 1970-01-01 22:00:00.000001415  19.609905
1438 1970-01-01 23:00:00.000001415  20.300540
1439 1970-01-02 00:00:00.000001415  17.534797

In [361]:
# Number of additional time steps to predict beyond the initial forecast horizon
additional_steps = 168  # For example, predicting 7 days ahead (24 hours * 7 days)

# Extend the forecast beyond the initial horizon
extended_forecast = result.get_forecast(steps=forecast_horizon + additional_steps, exog=exog.iloc[-(forecast_horizon + additional_steps):])

# Get the predicted values
predicted_values = extended_forecast.predicted_mean

# Extract the last timestamp from the train.csv data
last_timestamp = df['DATETIMEDATA'].iloc[-1]

# Generate a sequence of timestamps for the forecasted period
forecast_dates = pd.date_range(start=last_timestamp, periods=forecast_horizon + additional_steps + 1, freq='H')[1:]

# Create a DataFrame for the predicted values
predicted_df = pd.DataFrame({'DATETIMEDATA': forecast_dates, 'PM25_prediction': predicted_values})


predicted_df


DATETIMEDATA  PM25_prediction
1416 2024-02-29 00:00:00        20.075080
1417 2024-02-29 01:00:00        18.998370
1418 2024-02-29 02:00:00        18.331131
1419 2024-02-29 03:00:00        16.703528
1420 2024-02-29 04:00:00        18.749276
...                  ...              ...
1603 2024-03-07 19:00:00        18.607175
1604 2024-03-07 20:00:00        18.714532
1605 2024-03-07 21:00:00        18.501166
1606 2024-03-07 22:00:00        18.972411
1607 2024-03-07 23:00:00        16.830158

[192 rows x 2 columns]

In [349]:
#save to csv
predicted_values.to_csv('predict_hour.csv')

In [249]:
%pip install 'sktime'


77161.45s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
Note: you may need to restart the kernel to use updated packages.
